

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILURE = "GET_BOOK_FAILURE";



export const PATCH_BOOK_REQUEST = "PATCH_BOOK_REQUEST";
export const PATCH_BOOK_SUCCESS = "PATCH_BOOK_SUCCESS";
export const PATCH_BOOK_FAILURE = "PATCH_BOOK_FAILURE";